### ISSUE TITLE
DR2 models don't work at some zoom levels 

### ISSUE THREAD

**Issue by eteq** [legacysurvey/decals-web#11]
The DECALS-DR2-models don't seem to work at certain zoom levels.  I'm not clear exactly which work and which don't, but 12 seems to be consistently working, while higher zooms aren't...?

(Discussed this offline a bit with @dstndstn, and I think he found the fix, but asked me to record it here)

**Comment by dstndstn** [comment]
Could you check this now?  I think I fixed it...

**Comment by eteq** [comment]
Yep, seems to be fixed now - closing!
