### ISSUE TITLE
DR3 model cutouts seem to be slow (infinitely?) at zoom>13

### ISSUE THREAD

**Issue by eteq** [legacysurvey/decals-web#12]
I've noticed some odd behavior with the DECALS DR3 models over the web interface.  It appears that at zoom levels >13, getting cutouts is *much* slower than at lower zoom levels.  In some cases (but in a hard-to-reproduce fashion), they don't even return at all.

An example that shows this problem is http://legacysurvey.org/viewer/jpeg-cutout/?ra=318.4441&dec=2.4757&zoom=14&layer=decals-dr3-model&size=180

**Comment by dstndstn** [comment]
obsolete!
