### ISSUE TITLE
constraint DESI footprint and DESI positioners layers to have same center

### ISSUE THREAD

**Issue by sbailey** [legacysurvey/decals-web#26]
Currently the DESI footprint and DESI positioners outlines are completely independent.  If you turn them on at the same time, they line up correctly, but if you turn on one and then move before turning on the other, you can end up with a view where they overlap incorrectly.

Constrain the layers such that if you turn on a layer, it first checks if the other layer is already one and uses that center instead of the current view center.

@ziyaointl can you add this?

**Comment by ziyaointl** [comment]
Sure! I have a not-so-elegant solution in mind, but it should work. I will send a pull request in a few days.
