### ISSUE TITLE
Add brick support to "jump to object" form

### ISSUE THREAD

**Issue by sbailey** [legacysurvey/decals-web#35]
From @dstndstn in PR #32 to @ziyaointl :

> Would you consider adding the cool "Jump to object" search box shortcut for "brick" like you did for "DESI'? Bricks are the regions of sky that we do the image processing on, and are named like 2345p678, for RA=234.5, Dec=+67.8 (p = "plus", and m = "minus"). It already handles &brick=2345p678 in the URL, but it would be nice to also have it work in the search box.

+1 for @ziyaointl doing that.

[Asserting my own sense of GitHub organization on this by moving it into a new ticket instead of a post-merge comment request in a closed pull request.]

**Comment by dstndstn** [comment]
That was just the "high 5-s all around, what should we do next" phase of the ticket conversation :)

**Comment by ziyaointl** [comment]
Resolved by #39
