### ISSUE TITLE
Limit the size of external uploads

### ISSUE THREAD

**Issue by ziyaointl** [legacysurvey/decals-web#42]
As of now external uploads can get arbitrarily large depending on bandwidth within a timeout. Would be nice to instantiate a hard limit on the backend to prevent us from running out of disk space.

P.S. to @dstndstn , if you are busy with dr8 stuff, I'm happy to look into solutions and put together a pull request.

**Comment by dstndstn** [comment]
There should be a Django file uploads setting for this.
