### ISSUE TITLE
Jump To Object doesn't work on mobile

### ISSUE THREAD

**Issue by ziyaointl** [legacysurvey/decals-web#50]
For unknown reasons, the jump to object box in the lower left does not respond to clicks on iOS devices. I haven't tried Android yet.

**Comment by moustakas** [comment]
Doesn't work for me either (pixel running latest Android os).

**Comment by dstndstn** [comment]
I merged #51 and updated the dev and production versions -- could you please check if this issue is resolved?

**Comment by moustakas** [comment]
Works for me now!....on Chrome but not Firefox (where the search bar is actually not visible anymore).

**Comment by ziyaointl** [comment]
Works for me on iOS safari
